### ISSUE TITLE
SQLite 3.27.x

### ISSUE THREAD

**Issue by gennaios** [bvinc/go-sqlite-lite#21]
Hello, 

When you have a chance, an upgrade to the latest SQLite woul be appreciated. It has a new diacritic option for FTS.

Btw, I am considering switching to this module. The features sound great. It's possible I will inevitably. Do you have any benchmarks compared to the other driver and for example sqlx? It'd greatly help on deciding if I'd prefer to switch sooner or later.

**Comment by bvinc** [comment]
It's been upgrading to 3.28.0 just now!

Sorry, I don't have any benchmarks currently.  I would expect there could be some performance gains due to the connection pooling logic in `database/sql`, or possibly if another driver enters/exits C code more often than `go-sqlite-lite`.  `go-sqlite-lite` is pretty simple.  I'd love to see some benchmarks.  I might think about adding them at some point.

**Comment by gennaios** [comment]
Thank you. I also haven't done benchmarks but have noticed it is a bit faster. 3.28 also mentions some performance improvements but unsure if that'd make a difference in my use.
